# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Java project to Azure Function App - hw03menuexportapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: hw03menuexportapp
  PACKAGE_DIRECTORY: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3A9608D3365E448B938A879598F0BDEC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A8D21FB5F38C47139086FE9C2CE5A859 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3500C2033E9049AB879ABFD06BCA5B1E }}

      - name: Setup Java Sdk 17
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '17'

      - name: 'Restore Project Dependencies Using Gradle'
        shell: bash
        run: |+
            ./gradlew clean azureFunctionsDeploy
