# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Java project to Azure Function App - hw03pa200app

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: hw03pa200app # set this to your function app name on Azure
  PACKAGE_DIRECTORY: '.' # set this to the directory which contains pom.xml file
  JAVA_VERSION: '17' # set this to the java version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6BF44136D1194A43AA1DA4CE33EF57C5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_48518C6A8CC5456DB10D0F410F948AC3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5613867B3A6049E5886BA55C898072C1 }}

      - name: Setup Java Sdk 17
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '17'
      - name: 'Deploy using Gradle'
        shell: bash
        run: |+
            ./gradlew clean azureFunctionsPackage azureFunctionsPackageZip

      - name: 'Deploy'
        uses: Azure/functions-action@v1
        id: fa
        with:
            app-name: 'hw03pa200app'
            slot-name: 'Production'
            package: 'build/azure-functions/hw03menuexportapp'
